#!/system/bin/sh

write() {
  chmod 0644 "$1"
  echo "$2" > "$1"
}

write /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpu4/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpu5/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpu6/cpufreq/scaling_governor performance
write /sys/devices/system/cpu/cpu7/cpufreq/scaling_governor performance