#!/system/bin/sh

chmod 777 /sys/class/power_supply/*/*
chmod 777 /sys/module/qpnp_smbcharger/*/*
chmod 777 /sys/module/dwc3_msm/*/*
chmod 777 /sys/module/phy_msm_usb/*/*
echo '1' > /sys/kernel/fast_charge/force_fast_charge
echo '1' > /sys/class/power_supply/battery/system_temp_level
echo '1' > /sys/kernel/fast_charge/failsafe
echo '1' > /sys/class/power_supply/battery/allow_hvdcp3
echo '1' > /sys/class/power_supply/usb/pd_allowed
echo '1' > /sys/class/power_supply/battery/subsystem/usb/pd_allowed
echo '0' > /sys/class/power_supply/battery/input_current_limited
echo '1' > /sys/class/power_supply/battery/input_current_settled
echo '0' > /sys/class/qcom-battery/restricted_charging
echo '150' > /sys/class/power_supply/bms/temp_cool
echo '460' > /sys/class/power_supply/bms/temp_hot
echo '460' > /sys/class/power_supply/bms/temp_warm
echo '3000000' > /sys/class/power_supply/usb/current_max
echo '3000000' > /sys/class/power_supply/usb/hw_current_max
echo '3000000' > /sys/class/power_supply/usb/pd_current_max
echo '3000000' > /sys/class/power_supply/usb/ctm_current_max
echo '3000000' > /sys/class/power_supply/usb/sdp_current_max
echo '3000000' > /sys/class/power_supply/main/current_max
echo '3000000' > /sys/class/power_supply/main/constant_charge_current_max
echo '3000000' > /sys/class/power_supply/battery/current_max
echo '3000000' > /sys/class/power_supply/battery/constant_charge_current_max
echo '4600000' > /sys/class/qcom-battery/restricted_current
echo '3000000' > /sys/class/power_supply/pc_port/current_max
echo '3000000' > /sys/class/power_supply/constant_charge_current__max